# Generated by Django 5.1.2 on 2024-10-26 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IeltsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(choices=[('part_one', 'Part One'), ('part_two', 'Part Two'), ('part_three', 'Part Three')], max_length=20)),
                ('topic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('topic_questions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ielts Test',
                'verbose_name_plural': 'Ielts Tests',
                'db_table': 'ielts_test',
            },
        ),
        migrations.CreateModel(
            name='IeltsAnswersTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField(blank=True, null=True)),
                ('ielts_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts_test.ieltstest')),
            ],
            options={
                'verbose_name': 'Ielts Answers Test',
                'verbose_name_plural': 'Ielts Answers Tests',
                'db_table': 'ielts_answers_test',
            },
        ),
    ]
