# Generated by Django 5.1.2 on 2024-10-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ieltsanswerstest',
            name='ielts_test',
        ),
        migrations.RemoveField(
            model_name='ieltstest',
            name='topic_questions',
        ),
        migrations.CreateModel(
            name='IeltsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(blank=True, max_length=500, null=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ielts_test.ieltstest')),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
            },
        ),
        migrations.AddField(
            model_name='ieltsanswerstest',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ielts_test.ieltsquestions'),
        ),
    ]
